### ISSUE TITLE
[UMBRELLA] Requested Plugins

### ISSUE THREAD

**Issue by Issif** [falcosecurity/plugins#228]
In January 2022, Falco introduced its first version of a Plugin framework to extend its available inputs. The framework has been enhanced in the following months to have something production ready for adopters.

## Existing Plugins

We, the maintainers of Falco, created a bunch of Plugins to replace deprecated features (k8saudit) or to follow mediatic security events (Okta breach).

Right now, we have [registered](https://github.com/falcosecurity/plugins#registered-plugins) (excluding dummy plugins)

## SDK

To make the development of plugins easier, 2 SDK are provided: [Go](https://github.com/falcosecurity/plugin-sdk-go/) and [C++](https://github.com/falcosecurity/plugin-sdk-cpp). 
We can notice all plugins have been written in Go, it can be explained by several factors:
Go is easier to than C++
It’s a common language in web development, so in adopters’ infras
Falco’s ecosystem already embeds different Go codebases (Falcosidekick, Falcosidekick-UI, Falcoctl, Driverkit, Falco-exporter, Event-generator)

## Libs

Writing a plugin from scratch could be complicated for the contributors, this is why we could also provide libraries to keep them focus on the extraction logic and not the asides (auth, polling, create a web server, etc). The main goal of these libs is to avoid duplicate codes across plugins, allowing to keep an uniformity.

This approach has been started with 2 libs for AWS:
- [AWS Session](https://github.com/falcosecurity/plugins/tree/master/shared/go/aws/session): allows to create easily a session for AWS API
- [AWS Cloudwatch](https://github.com/falcosecurity/plugins/tree/master/shared/go/aws/cloudwatchlogs): allows to set filters and starts the polling of log entries from Cloudwatch

To “open” Falco to more sources, we could create shared libs for generic usages:
- Web Server: to collect JSON webhook payloads
- File reader: to follow new entries in a file
- Kafka: to be a consumer of a topic
- SQS: to poll a queue
- RabbitMQ: to be a consumer of an exchange
- MQTT: for IoT

We also need to address the most common Cloud Providers and their specific log aggregator systems with the basic functions which are:
- Authentication to the API
- Creation of a client for the log service
- Gathering of logs
- Looping over the results

By providing these libs, it will be easier for developers to create new plugins for specific usages with these Cloud Providers.

## Plugins

The purpose of this issue is to list the requested plugins by the community, the volunteers to develop them and their statuses.

The following table will be kept updated to avoid people to search through N issues.

<table>
    <thead>
        <tr>
            <th scope="col">Plugin</th>
			<th scope="col">Description</th>
            <th scope="col">Issue #</th>
            <th scope="col">Developer</th>
            <th scope="col">Repo URL</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
	<tr>
		<td> k8saudit-gke
		<td> Collect K8S Audit Logs from GKE
		<td> 
		<td> @sboschman
		<td>
		<td> Completed
	</tr>
	<tr>
		<td> k8saudit-aks
		<td> Collect K8S Audit Logs from AKS
		<td> #123
		<td> @NissesSenap
		<td>
		<td> In Progress
	</tr>
	<tr>
		<td> k8saudit-openshift
		<td> Collect K8S Audit Logs from OpenShift
		<td> 
		<td> 
		<td>
		<td> Requested
	</tr>
	<tr>
		<td> redshift
		<td> Collect Audit Logs from Redshift
		<td> #117 
		<td> 
		<td>
		<td> Requested
	</tr>
	<tr>
		<td> slack
		<td> Collect Audit Logs from Slack
		<td> 
		<td> 
		<td>
		<td> Requested
	</tr>
	<tr>
		<td> k8saudit-admission
		<td> Collect Audit Logs from K8S Control Plane through an admission controller
		<td> 
		<td> @RichardoC
		<td> https://github.com/RichardoC/k8sadmission
		<td> In Progress
	</tr>
</table>

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/plugins/issues/243
- [ ] https://github.com/falcosecurity/plugins/issues/368
- [ ] https://github.com/falcosecurity/plugins/issues/123
```

**Comment by Issif** [comment]
@NissesSenap no problem, I get that. If you have a WIP repo, please share it as reference

**Comment by NissesSenap** [comment]
Sadly, I never got that far

**Comment by Issif** [comment]
Np

**Comment by sboschman** [comment]
Hi, I have been working on a `k8saudit-gke` plugin. Currently I have it deployed in our Falco pipeline to test drive. Still needs a bit of documentation and code cleanup, so it is not ready for a pr yet.

Once I am ready to open a pr, is anyone from the Falco team willing to assist in getting it merged into the plugins codebase? Helping out with practical stuff like reserving a plugin ID, maybe bumping the go version in the ci workflow and having the ci rule validator accept gke specific modification rules (1). Can you arrange help @Issif , or ?

---
(1) It seems the validator only accepts a complete rule with all fields. The gke specific rules file I made uses the new override section to modify the k8s audit rules from the `k8saudit` plugin, so the gke specific stuff is not in the default/base/standard k8saudit rules file.
I noticed the default k8saudit rules do contain EKS specific rule extensions. My concern is this might compromise the effectiveness of Falco's threat detection. For example EKS system 'users' (like `eks:node-manager`) are excluded from triggering rules. I can imagine these system user names are protected/enforced by EKS, and you can not create them yourself. But on a different cloud these names might not be protected, allowing a shady person to use these usernames to bypass Falco's detection rules.

**Comment by Issif** [comment]
I can help you for sure. For the CI, we need to see with @jasondellaluce too
